### ISSUE TITLE
Pickle load error when running demo. Does this repo use Python 2 or Python 3? :(

### ISSUE THREAD

**Issue by andrewjong** [akanazawa/hmr#100]
I get this when I run the demo.

```
File "src/tf_smpl/batch_smpl.py", line 32, in __init__
dd = pickle.load(f, encoding="latin-1") 
TypeError: load() got an unexpected keyword argument 'encoding'
```

Only Python3 has an "encoding" keyword argument for pickle.load(), yet the Readme says to use Python2.7. What should I do here?

Further more, demo_webcam is using print statements from Python 3 and not Python 2. It really is quite confusing.

**Comment by andrewjong** [comment]
Removing the "encoding" kwarg fixes this issue.

Adding the standard from __future__ import blah fixes the demo_webcam.py. Still needs to be fixed in the code base, however.

**Comment by alon1samuel** [comment]
I also ran into that problem. I would like the master branch to be changed, not sure if it's still up to changes.
