### ISSUE TITLE
Issue with OPenDR

### ISSUE THREAD

**Issue by eng100200** [akanazawa/hmr#101]
@akanazawa   Hello and all other users, i have an issue in installing OpenDR , i have tried python 3.5 and python 2.7.15 on both versions i could not able to install opendr. Now, should i remove opendr from the demo code or what should i do to install it?

**Comment by Justinemmerich** [comment]
I had the same problem with an similar project try downgrade to `python2.7` with `opendr==0.77` hope this helps but didn't tested it on this project
