### ISSUE TITLE
OPenDR

### ISSUE THREAD

**Issue by xiayizhan2017** [akanazawa/hmr#103]
python2.7.12,ubuntu16.04
opendr7.6
I download the OSMesa.Linux.x86_64.zip file in opendr/contexts.

when I run python setup.py build, it is a wrong.
building 'contexts.ctx_mesa' extension
x86_64-linux-gnu-gcc: error:contexts/ctx.mesa.c: There is no such file or directory.

**Comment by jszgz** [comment]
How did you solve it？

**Comment by firstmover** [comment]
How did you solve it?
