### ISSUE TITLE
Can you share human3.6m moshed parameters?

### ISSUE THREAD

**Issue by bebory** [akanazawa/hmr#104]
Hi, I am interested in the 3D reconstruction of human body. Can you share the human3.6m moshed data, like shapes and poses? Thank you very much!

**Comment by akanazawa** [comment]
Unfortunately I can't due to licensing issues. Please request the authors of Human3.6M for permission, with their permission I could. Best,

Angjoo

**Comment by bebory** [comment]
Hi, Angjoo,
    Sorry that I sent emails to authors of Human3.6M for permission, but the have not replied to me. While I have got the permission to access the human3.6m data itself from its author some time ago, as shown in the image below.  And I am very hurry to use these moshed SMPL parameters data because the deadline of AAAI, 9.5. 
    Could you please share me these moshed SMPL parameters of human3.6m for research purpose？ Thanks very much!


    Best Wishes!


    zhoujian











------------------ 原始邮件 ------------------
发件人: "akanazawa"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 凌晨5:24
收件人: "akanazawa/hmr"<hmr@noreply.github.com>; 
抄送: "周健"<2239131181@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [akanazawa/hmr] Can you share human3.6m moshed parameters? (#104)




Unfortunately I can't due to licensing issues. Please request the authors of Human3.6M for permission, with their permission I could. Best,
 
Angjoo
