### ISSUE TITLE
Using discriminator to identify human or not

### ISSUE THREAD

**Issue by alon1samuel** [akanazawa/hmr#108]
Hi, 

I'm using the demo of the 3D human mesh. I've wanted to use the discriminator to know weather there is a person in the frame or not. 
I couldn't find it, does anyone knows by any chance? 

Thanks, regards

Alon

**Comment by akanazawa** [comment]
The code is designed to only see bounding boxes where humans exist, so this is not something that is provided in this project. I suggest using an off-the-shelf human detector.
