### ISSUE TITLE
can't untar models.tar.gz: `gzip: stdin: not in gzip format`

### ISSUE THREAD

**Issue by neonb88** [akanazawa/hmr#11]
Hi,

I downloaded model.tar.gz from https://people.eecs.berkeley.edu/~kanazawa/cachedir/hmr/models.tar.gz and then I run `tar -xvzf` and get the following error.  See Stacktrace:

```
tar -xvzf models.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I'm surprised no one else has reported this problem.  I must be overlooking something stupid.  system info: Ubuntu 16.04, 64-bit

Thank you!

**Comment by neonb88** [comment]
Got it.  The correct command is:

`tar -xf models.tar.gz`

**Comment by ashokreddy121** [comment]
hi 
I got the same issue but i can't resolve
