### ISSUE TITLE
Pipeline of Moshing Human3.6M

### ISSUE THREAD

**Issue by Hhhhhhhhhhao** [akanazawa/hmr#114]
Hi, can you please state the pipeline of Moshing Human3.6M to get their SMPL parameters? 
It's the last step before I can re-produce your results.

**Comment by LH-Abner** [comment]
hello，do you have got the human3.6m_tf_dataset?  can you copy the code human3.6m_to_tfrecord.py to me ? thanks! my email is lhabner2012@gmail.com

**Comment by hanabi7** [comment]
i also need the code human3.6m_to_tfrecord.py. can you copy the code to me~~thanks, my email is knight43967@163.com

**Comment by akanazawa** [comment]
The pipeline is described in the original Mosh paper, and also in this latest [AMASS ](https://amass.is.tue.mpg.de/) paper I believe. Mosh is not my project so I cannot share it. 
As for human3.6m_to_tfrecords.py,, there is a video version in HMMR code: https://github.com/akanazawa/human_dynamics/blob/master/src/datasets/h36_to_tfrecords_video.py
it's basically the same thing except this packages it for video. Hope this helps.

Best,

A

**Comment by ozhyo** [comment]
Hi, could you please send the tfrecords dataset of human3.6m to me ? Thanks s lot! @Hhhhhhao @LH-Abner @hanabi7
