### ISSUE TITLE
H36M metadata

### ISSUE THREAD

**Issue by xjturobocon** [akanazawa/hmr#115]
Hey,

I read the code of Human_dynamics, In  human_dynamics/src/datasets/h36/read_human36m.py, 
'xml_path = join(raw_data_root, 'metadata.xml')'. I didn't find metadata.xml in H36M website. Where should I get this file?  Thanks.

**Comment by akanazawa** [comment]
This was released with the Human3.6M dataset, seems like they have it: https://github.com/anibali/h36m-fetch
