### ISSUE TITLE
Question about mosh data

### ISSUE THREAD

**Issue by Mercurialzhang** [akanazawa/hmr#119]
Hi, thanks for your excellent work. I'm trying to reappearing your work recently, sadly the mosh result of Human3.6m is not available any more. I have downloaded Human3.6m from official site, how can I generate the mosh result from raw H36m data?
Looking forward to your reply, Thanks!

**Comment by Karol-Perec** [comment]
Hey, did you manage to get mosh data or the way to generate it? Thank you for reply

**Comment by JackSyu** [comment]
@Mercurialzhang Hi, did you get access of h36m Mosh result? If you did, could you tell me how to get it? For example, contact the author of Mosh? Thank you very much.
