### ISSUE TITLE
code for human part segmentation

### ISSUE THREAD

**Issue by penincillin** [akanazawa/hmr#12]
Great work and thanks for make the code public available.
Human part segmentation was mentioned in your paper and I am wondering have you made part of this work public available?

**Comment by akanazawa** [comment]
Hi,

I have not yet,,, but I just use the part segmentation code from [Unite the people code base](https://github.com/classner/up). You can take a look at this until I come around to this.

Thanks!

Angjoo

**Comment by nicolasugrinovic** [comment]
@akanazawa thank you for pointing out the code in UP. Is is safe to assume that once we have the mesh and the ability to render it, we can get (in a very straight forward manner) human part segmentation?
