### ISSUE TITLE
how to get theta for original image

### ISSUE THREAD

**Issue by sandhyalaxmiK** [akanazawa/hmr#120]
Hi,
Nice work. So many application for this. Found hmr as a base in many repositories.
My image is of some different size like 560*1640 (width*height). Obtained theta (cams,pose,shape) are for size 224*224 . How to regain the values of theta for pose, shape parameters??

Thanks in advance.
Regards,
SandhyaLaxmi

**Comment by akanazawa** [comment]
The theta and beta are independent of the camera, so they should not change. If you want the camera parameters in the original input image, [this function](https://github.com/akanazawa/hmr/blob/6d3d4c3631897ffe6cc00ac65cb6fb0db574560c/demo.py#L45) computes that. If you send in the 2D joints to determine the location of the person as described, it should already render the person in the original input image resolution.
