### ISSUE TITLE
About smpl_faces.npy

### ISSUE THREAD

**Issue by dbgns** [akanazawa/hmr#121]
Could someone explain what's the meaning/structure of the smpl_faces.npy? I have noted that there are 13776 rows in this file and according to the comments in the code, each row is i_a, i_b, i_c. In my understanding, this is the index of the vertex in SMPL's 6890 vertices, is it correct? And what's the use of smpl_faces.npy? It seems that it isn't the actual **faces** of human, right?

**Comment by Stephenfang51** [comment]
> Could someone explain what's the meaning/structure of the smpl_faces.npy? I have noted that there are 13776 rows in this file and according to the comments in the code, each row is i_a, i_b, i_c. In my understanding, this is the index of the vertex in SMPL's 6890 vertices, is it correct? And what's the use of smpl_faces.npy? It seems that it isn't the actual **faces** of human, right?

请问您对这个file有想法了吗 ？ 可否简单的解释一下 谢谢 ！

**Comment by dbgns** [comment]
> > Could someone explain what's the meaning/structure of the smpl_faces.npy? I have noted that there are 13776 rows in this file and according to the comments in the code, each row is i_a, i_b, i_c. In my understanding, this is the index of the vertex in SMPL's 6890 vertices, is it correct? And what's the use of smpl_faces.npy? It seems that it isn't the actual **faces** of human, right?
> 
> 请问您对这个file有想法了吗 ？ 可否简单的解释一下 谢谢 ！

这个face可能翻译成“面”更合适，每一行就代表一个面，这里一行是三个元素 i_a, i_b, i_c，即代表这个面有三个顶点，即这个面是三角形，这里的顶点引用的是6890的顶点中的点，元素的值代表顶点在6890个点中的索引。
这个文件涉及到CG(计算机图形学)里的知识，大概就是说这个面会在渲染, 光栅化(rasterization)的时候用到，用来确定落在这个面(这里也就是三角形)内像素的RGB值，具体可以google一下，我不是很懂

**Comment by monacv** [comment]
How do you visualize the smpl_faces.npy file?
