### ISSUE TITLE
Is there any possiblity to generate training Mosh data from Human 3.6m dataset?

### ISSUE THREAD

**Issue by Karol-Perec** [akanazawa/hmr#123]
Hey!
I got newest Human 3.6m dataset and I've read that this is not a dataset prepared for use in hmr anymore. I've seen that you process H3.6m in your another project: /human_dynamics. Can processing scripts be used in this project to prepare proper h3.6m moshed data that will be working?

**Comment by akanazawa** [comment]
Unfortunately Mosh data for Human3.6M is not available for licensing reasons. However there are new datasets [AMASS](https://amass.is.tue.mpg.de/) that has Mosh data for many other mocap datasets. So please take a look at that. 
But yes you can use that pre-processing in human_dynamics as a starting point, that one processes it for video but here you just need a single image.
