### ISSUE TITLE
when run demo_camera.py, there are always joint information errors.

### ISSUE THREAD

**Issue by zhangkai95** [akanazawa/hmr#127]
When I run demo_camera.py, sometimes the verts or joints3d information of some frames are incorrect，for example，Swap left and right. 
However, run demo.py for each image, this will not happen.

Hope to get your explanation, thank you very much!

**Comment by akanazawa** [comment]
I think it is just that the input image you're using is a challenging one -- this is still a learning based algorithm and not perfect. There are more recent models, like [SPIN](https://github.com/nkolot/SPIN), which may be more accurate.

Best.
