### ISSUE TITLE
can we retrain model to accept images with resolution higher than 224x224?

### ISSUE THREAD

**Issue by Naveennavik** [akanazawa/hmr#129]
Hi @akanazawa @AdityaAS , can the model be retrained or fine tuned to accept images with resolution higher than 224x224? 

Thanks in advace.

**Comment by akanazawa** [comment]
Sure! just re-write the data loader to return a bigger image and retrain.

**Comment by Naveennavik** [comment]
I dont seem image to be resized in dataloader if it so can u say me on what line to change?

**Comment by akanazawa** [comment]
https://github.com/akanazawa/hmr/blob/bce0ef9b90bd36871d2aff8688b2682170cd365a/src/data_loader.py#L56

Best,

A
