### ISSUE TITLE
line 167 of file 'mpii_to_tfrecords.py'

### ISSUE THREAD

**Issue by auzyze** [akanazawa/hmr#13]
Thanks for sharing the code.

Could you have a look at the line 167 of file 'mpii_to_tfrecords.py', looks like it should be moved outside of the outer "if/else" block.

**Comment by MandyMo** [comment]
here is my pytorch version of HMR:
https://github.com/MandyMo/pytorch_HMR

**Comment by akanazawa** [comment]
You're right! Thanks!!! Fixed.
