### ISSUE TITLE
license

### ISSUE THREAD

**Issue by wine3603** [akanazawa/hmr#134]
Hi @akanazawa ,
Thanks for sharing your nice work,
I didn't find the license about your work,
could you tell me which license HMR?
Is it under MIT License?

**Comment by akanazawa** [comment]
Please find our license here:
https://github.com/akanazawa/hmr/blob/master/LICENSE

Note that only the code is under MIT, for libraries such as SMPL and other
datasets, their original licensing must be followed.

Best,

A
