### ISSUE TITLE
Is there a pose data set?

### ISSUE THREAD

**Issue by OOF-dura** [akanazawa/hmr#136]
HMR uses a discriminator on SMPL's pose. I would like to ask if there is a way to **sample** the pose. For example, you can get the corresponding pose according to the category: running pose, akimbo pose, dancing pose, sitting pose, etc.

**Comment by akanazawa** [comment]
You can certainly sample from the Moshed mocap data (provided here or at [AMASS](https://amass.is.tue.mpg.de/) ), however the model presented in HMR is not generative, so you can't sample from that.  You maybe interested in looking at Vposer: https://github.com/nghorbani/human_body_prior

Best,

A
