### ISSUE TITLE
female and male models

### ISSUE THREAD

**Issue by hosnasattar** [akanazawa/hmr#140]
is it possible to provide female and male models? I tried to use the SMPL female model but it seems you have some regression in addition to SMPL model into it so I can not use them directly.

**Comment by jszgz** [comment]
Hello, do you know how to use mpi_inf_3dhp_to_tfrecords.py to convert mpi_inf_3dhp dataset? I failed because the code use jpg as input but the dataset I downloaded is consisting of videos. Do I need to use ffmpeg and write code to convert avi to jpg?

**Comment by akanazawa** [comment]
This repo uses the neutral SMPL models, so you can't immediately use its output for gendered models. 
There are more recent approaches that use gendered models: https://github.com/vchoutas/smplify-x

Best,

A
