### ISSUE TITLE
Using CMU's OpenPose with facial and hands keypoints

### ISSUE THREAD

**Issue by jaygit123** [akanazawa/hmr#143]
Hi,
Thanks for the code. 
I need facial expressions and hands / fingers as well in the resultant bvh file. So, I am looking to use CMU's OpenPose (instead of keras_Realtime_Multi-Person_Pose_Estimation). 

Has anyone tried with CMU OpenPose and succeeded in including facial expressions and hands/fingers motions as well in the bvh? Do let me know.

**Comment by jaygit123** [comment]
Hi @akanazawa,
Could you help with the above request please? 

Thanks.

**Comment by jszgz** [comment]
Hello, do you know how to use mpi_inf_3dhp_to_tfrecords.py to convert mpi_inf_3dhp dataset? I failed because the code use jpg as input but the dataset I downloaded is consisting of videos. Do I need to use ffmpeg and write code to convert avi to jpg?

**Comment by akanazawa** [comment]
Yes if you have more keypoints you can setup new terms in the reprojection loss and train with them. 
See SMPLify-X: https://github.com/vchoutas/smplify-x that goes in this direction.

Yes you need to write them out to frames. 

Best,

A
