### ISSUE TITLE
How to convert the predicting result to a 3D file like STL file

### ISSUE THREAD

**Issue by ZheWalk** [akanazawa/hmr#152]
Hi, thank you for sharing!
I wish to convert the demo result into a 3D file. 
Does the npy file "hmr-master\src\tf_smpl\smpl_faces.npy" contain points clouds coordinate information?
How can I analyze it?

**Comment by akanazawa** [comment]
Hi thanks, please see: https://github.com/akanazawa/hmr/issues/26
There are couple more if you google "obj" in the issues. 

Best of luck!

A
