### ISSUE TITLE
Training the discriminator

### ISSUE THREAD

**Issue by zhangy76** [akanazawa/hmr#154]
Hi,

Thanks for proposing this classic work! When training the model only using 2D keypoints and pose prior, I wonder how many epochs do we need so that the model can output realistic body reconstruction? Also, why don't we need an Sigmoid function on the output of discriminator?

Thanks,
Yufei

**Comment by akanazawa** [comment]
Thanks Yufei. I forget how long really,, but in my recollection realistic poses start happening very quickly. From then on, is a matter or training the regressor so that reprojection loss is minimized. 
We don't need this bc we use Least-Squared GAN objective for the discriminator. 

Best,

A

**Comment by amituofo1996** [comment]
Hi,

I could not find discriminators based datasets , can you help me ?

**Comment by amituofo1996** [comment]
Hi,
I am confused about which dataset is used in training discriminators, is h3.6m moshed data, or mpi-inf-3dhp dataset ?
Thanks!

**Comment by akanazawa** [comment]
It is the moshed datasets, bc the data has to be in SMPL format. moshed h36m is not available anymore, but the other datasets still are (through link on readme) and you can also use AMASS https://amass.is.tue.mpg.de/

Best,

A
