### ISSUE TITLE
Changing SMPL model with a custom mesh

### ISSUE THREAD

**Issue by amirjaber** [akanazawa/hmr#158]
Thanks for sharing this code. I am wondering if it is possible to replace SMPL model with just upper body mesh, create dataset with 2d and 3d keypoints, camera locations and retrain the model with this new mesh?

**Comment by akanazawa** [comment]
You can simply modify this code base to only train with upper body keypoints and just disregard the lower body when you render! (just need to re-fix the mesh, a quick hack is identify all lower body vertices and collapse them to a single vertex).
