### ISSUE TITLE
[Opensource contributions] 2D-to-3D color mapping

### ISSUE THREAD

**Issue by layumi** [akanazawa/hmr#159]
Hi @akanazawa 
Thanks a lot for the great code. 
I add the 2D-to-3D color mapping function in the final `obj` file at https://github.com/layumi/hmr. 
It would be great if you can consider to include the link in the [Opensource contributions]. 
I hope it may help other beginners in the community.  Thanks a lot~~

![Teaser Image](https://github.com/layumi/hmr/blob/master/demo.png)

**Comment by akanazawa** [comment]
Cool!! updated, thanks :)!
