### ISSUE TITLE
Get 3D model

### ISSUE THREAD

**Issue by ogata2606** [akanazawa/hmr#17]
Thank you for opening code.
I could get images of model, but are there any way to get 3D model?
I'd like to see model from a lot of directions.

**Comment by Dawars** [comment]
You will need to download it from the [SMPL](http://smpl.is.tuebingen.mpg.de/) project site.
The code there can export to OBJ.

**Comment by MandyMo** [comment]
https://github.com/MandyMo/pytorch_HMR

this is my pytorch version of the code.
