### ISSUE TITLE
Cocoplus joint order

### ISSUE THREAD

**Issue by blzq-sh** [akanazawa/hmr#18]
Hi, 

Would it be possible to share the joint order of the 19 cocoplus joints returned by the SMPL model code, as well as the 24 joints of the original SMPL model?

**Comment by MandyMo** [comment]
https://github.com/MandyMo/pytorch_HMR

this is my pytorch version of the code.

**Comment by blzq-sh** [comment]
This is the output order for the COCO joints:
```
#  0: RAnkle
#  1: RKnee
#  2: RHip
#  3: LHip
#  4: LKnee
#  5: LAnkle
#  6: RWrist
#  7: RElbow
#  8: RShoulder
#  9: LShoulder
# 10: LElbow
# 11: LWrist
# 12: Neck
# 13: Head (top of)
# 14: Nose
# 15: LEye
# 16: REye
# 17: REar
# 18: LEar
```

**Comment by Superlee506** [comment]
@blzq-sh Hi, Thanks for this joint order information. Do you know how to compute the "cocoplus_regressor (6890 x 19)"  matrix. In the paper, the author point out that:
![image](https://user-images.githubusercontent.com/13114675/45531590-06aa7280-b823-11e8-8d88-83f2c1fc0f5b.png)
I refer to these papers, and they  also don't make it clear.

**Comment by Lixz123456** [comment]
How did you get it, @blzq-sh ,I can't find the official version
