### ISSUE TITLE
Created Docker file

### ISSUE THREAD

**Issue by Dawars** [akanazawa/hmr#19]
I created a docker image for this project: https://hub.docker.com/r/dawars/hmr/

I only tested the `demo.py` so far. The matplotlib figures **can't be displayed** but should be saved to file instead.

Hope you find it useful.

**Comment by MandyMo** [comment]
https://github.com/MandyMo/pytorch_HMR

this is my pytorch version of the code.

**Comment by akanazawa** [comment]
Great! I added both of your contributions on the README page. Thank you!!

**Comment by msj121** [comment]
@Dawars Thanks for sharing docker image. I am trying to run the docker you made. I am new to using it with python. I tried: docker run dawars/hmr
 
and it just stays on:

    ```
Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=22b86f65028acc56c8798a33644d05bea3a8c9e91f87c40a
```

I pointed my browser there but didn't connect. I am using aws.
