### ISSUE TITLE
Could you tell me how you pre-compute pose data in Human3.6M?

### ISSUE THREAD

**Issue by shanYanGuan** [akanazawa/hmr#20]
Dear @akanazawa , thanks for your work.
I am a new guys in 3D pose. In [Human3.6M](http://vision.imar.ro/human3.6m/description.php), they provide joint angle(KR) and 3D positions(xyz). But i can link those two format to you pre-compute dataset. Could you tell me how to deal with it?

**Comment by shanYanGuan** [comment]
gt3d is represented by Eular angle?

**Comment by akanazawa** [comment]
Hi, 

`mosh/gt3d` corresponds to the ground truth 3D positions (xyz). Hope you figured it out.

**Comment by shanYanGuan** [comment]
I have a question:
   human3.6M, humaneva  or other dataset provide skeleton joints in camera cooradiate. For example, human3.6M provide mono format and image format. SHould I normallize them to -1~1? Or I can just input them.
