### ISSUE TITLE
Not able to reproduce result.

### ISSUE THREAD

**Issue by tejanmehndiratta15** [akanazawa/hmr#22]
System details:

Ubuntu 18.04

I have been trying to run the demo file since last night. but It still not showing anything in output. it just stop wihout any error starting python console.

Here is the terminal logs.
mirrorsize@mirrorsize-Latitude-E6420:~/HMR$ python demo.py --img_path /home/mirrorsize/HMR/data/random.jpg
Iteration 0
Iteration 1
Reuse is on!
Iteration 2
Reuse is on!
Restoring checkpoint /home/mirrorsize/HMR/src/../models/model.ckpt-667589..
Resizing so the max image size is 224..
/home/mirrorsize/HMR/src/util/renderer.py:313: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(image.dtype, np.float):
--Return--
None
> /home/mirrorsize/HMR/demo.py(91)visualize()
     90     import ipdb
---> 91     ipdb.set_trace()
     92 

ipdb> 

Can anyone help with this?

**Comment by nitin-ppnp** [comment]
It seems ipython debugger breakpoint. Comment this line (line 91)

**Comment by tejanmehndiratta15** [comment]
Commenting the line 91 is doing nothing. The whole process runs end-to-end without producing any errors or output.

**Comment by nitin-ppnp** [comment]
From your logs, it seems like you are entering into ipython debugger. Just remove line 90 and 91, or comment them to avoid entering into it. Or just type 'c' and press enter to continue execution.

**Comment by tejanmehndiratta15** [comment]
Yes, I did that too. Nothing is happening when I press enter, the ipython debugger is still on.
Would you please send me your version of this repo which you ran on this machine?

**Comment by akanazawa** [comment]
This is probably a problem with matplotlib. It's supposed to show a matplotlib drawing window.
If you're trying to do this through ssh or something without X it wouldn't work.

First please make sure that in python you can plot something with matplotlib. Like something like below should plot an image for you:
```
import numpy as np
import matplotlib.pyplot as plt
plt.figure(1)
plt.imshow(np.random.rand(100, 100, 3))
plt.show()
```

**Comment by Hosseinhashemiir** [comment]
@akanazawa  there is no problem with Matplotlib codes but I have the same error like @tejanmehndiratta15

**Comment by Hosseinhashemiir** [comment]
@akanazawa  there is no problem with Matplotlib codes but I have the same error like @tejanmehndiratta15  
I would be thankful for any suggestion or solution.

**Comment by akanazawa** [comment]
Did you try what I just suggested and does it plot an image for you? Sorry but I can't support thing for matplotlib.
