### ISSUE TITLE
Compensation for changing camera parameters in a video sequence

### ISSUE THREAD

**Issue by nitin-ppnp** [akanazawa/hmr#23]
I am running HMR on a video sequence. After completion, I get **Theta** (85X1) for each frame. For visualization, I used **Theta[3:75]** for SMPL pose and **Theta[75:85]** for SMPL shape. The visualized mesh sequence seems to be incorrect and I think it is because I am not taking care of the inferred camera parameters i.e. **Theta[0:3]**. 
I am not sure what exactly **_get_original_** function in _**renderer.py**_ does, but I suspected it compensates for the camera parameters. So , I tried visualizing the vertices given by _**get_original**_ function and it looks a bit better. Am I correct?

**Comment by akanazawa** [comment]
Hi,

Yes the `get_original` is a bit complicated, but here is a description of what it's doing:
1. HMR recovers the camera [s, tx, ty] in the input image frame of 224 x 224 (actually in a normalized space, of [-1, 1] corresponding to this input). However the original image is not always 224x224, we scaled the image and cropped them for eg using openpose detection so we have the person centered in a 224x224 region.
These scale and crop parameters were saved as `proc_param`, where `scale` is the scale factor, and `start_pt` is the crop starting point after preprocessing.
2. `get_original` recovers the rendering camera settings s.t. it overlays the person in this original image, undoing the scale and crop. I'm using the OpenDR renderer s.t. the camera is always at identity, and I just need to specify the image size, focal length, and principal point, to render an arbitrary mesh in the world coordinate. So you need to figure out the focal length and principal point, and the `z` translation of the human body:
-  Because OpenDR is a perspective camera (but HMR recovers weak-persepective), I make an assumption about the focal length and to recover the global `z` translation of the mesh in the world coordinate. (The scale `s` that HMR recovers is essentially `focal_length/z`.) I also "undo" the scaling done to the original image here.
 - Then Adjust the principal point of the camera s.t. it's on the center of the bounding box in the original input image space.

Hope this helps.

**Comment by akanazawa** [comment]
Hi,

No the camera is weak-perspective (or scaled orthographic):
https://github.com/akanazawa/hmr/blob/4e7afb919ef5cb6a69b7a7b3792cedee8d6d8491/src/tf_smpl/projection.py#L29
Note that the projection gets scaled in the end. Camera is [scale, tx, ty].
The global rotation is part of the pose (it's object centric).

Best,

Angjoo

**Comment by Yuliang-Zou** [comment]
Thanks for the clarification. I understand it now.

**Comment by akanazawa** [comment]
Np!! Thanks for your interest!

**Comment by Superlee506** [comment]
@akanazawa @Yuliang-Zou, I want to run HMR on a video sequence, but the resulted model jitters. Are there some methods can smooth results between the successive frames.

**Comment by akanazawa** [comment]
Hi,

We recently proposed a post-processing smoothing algorithm on our recent [SIGGRAPH Asia paper](https://xbpeng.github.io/projects/SFV/index.html), I plan to release that part of the code around the time of paper presentation (in early December) but not sure when exactly.. If you're interested it's not very hard to implement on your own. 

Best,

Angjoo

**Comment by Superlee506** [comment]
@akanazawa Hi, ANGJOO KANAZAWA, the suggested [SIGGRAPH Asia paper,](https://xbpeng.github.io/projects/SFV/index.html) is really related to my question. After reading this paper, I have two questions:
(1). In "**Section 6 MOTION RECONSTRUCTION** ",  do you just optimizing the Encoder's param with the following loss fucntion:
![image](https://user-images.githubusercontent.com/13114675/47135397-a192e280-d2e2-11e8-9f6a-e31b969751c7.png)
or 
along with the loss function
![image](https://user-images.githubusercontent.com/13114675/47135453-e0c13380-d2e2-11e8-96ef-aa7bf82ac1be.png) and optimizing the Encoder, Decoder and Discriminator?

(2) As we know the 3D human pose estimated by [Openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) is 3D coordinates (x, y, z) of each joint, how can we get the local rotation of each joint? In the suggested paper, the  3D consistency loss is calculated through the local rotation of joints.

Thanks again, and looking forward to your reply.

**Comment by Superlee506** [comment]
@akanazawa Hi, ANGJOO KANAZAWA, the suggested [SIGGRAPH Asia paper](https://xbpeng.github.io/projects/SFV/index.html), is really related to my question. After reading this paper, I have two questions:
(1). In "Section 6 MOTION RECONSTRUCTION ", do you just optimizing the Encoder's param with the following loss fucntion:
![image](https://user-images.githubusercontent.com/13114675/47135741-14e92400-d2e4-11e8-84fd-e41c09f8cd12.png)
Or along with the loss function:
![image](https://user-images.githubusercontent.com/13114675/47135789-36e2a680-d2e4-11e8-998e-c97d4b297e04.png)

and optimize the Encoder, Decoder and Discriminator?

(2) As we know the 3D human pose estimated by [Openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) is 3D coordinates (x, y, z) of each joint, how can we get the local rotation of each joint? In the suggested paper, the 3D consistency loss is calculated through the local rotation of joints.

Thanks again, and looking forward to your reply.

**Comment by akanazawa** [comment]
Hi @Superlee506 ,

In the SIGGRAPH Asia paper, during motion reconstruction we fix all of the HMR network's parameters, and only update the intermediate features `Z`. So we only minimize the first equation you put there wrt to `Z` and we don't do anything with the second equation you put there that's for the encoder & decoder. 
You can just think of it as searching for the best `Z` that minimize the `l_rec(Z)`, with fixed decoder (HMR's 3D regressor).

(2) Openpose only returns 2D keypoints. I believe their 3D joint prediction requires multiple views, which are not available. The local rotation of each joint is obtained by HMR. The 3D consistency loss is against the initial single-view HMR output. We want the newly smoothed joint rotations obtained by the optimization, to be close to the confident initial single-view HMR output, s.t. motions do not get overly smoothed out. The confidence is measured by the reprojection error of the initial pose. 


Hope this clears things up.

Best,

Angjoo

**Comment by Superlee506** [comment]
@akanazawa I'm a little confused about the first question, do you take the intermediate features **Z** as param and optimize **Z** ?  So, the total number of  param is related to the number of frames?

**Comment by akanazawa** [comment]
Yes, you're correct, it's because we want to smooth the predictions for all N frames. Btw we did optimization in the Z space (N x 2048), but it could have also done in the output space, in which case the opt parameter will be (N x 85).

**Comment by thanhkien84** [comment]
> Hi,
> 
> We recently proposed a post-processing smoothing algorithm on our recent [SIGGRAPH Asia paper](https://xbpeng.github.io/projects/SFV/index.html), I plan to release that part of the code around the time of paper presentation (in early December) but not sure when exactly.. If you're interested it's not very hard to implement on your own.
> 
> Best,
> 
> Angjoo

Hi Angioo, have you got any updates on this release yet?

**Comment by akanazawa** [comment]
Hi @thanhkien84, 

The end of year has been hectic and I haven't gotten to this yet.. I will aim to do this in January.

Best,

Angjoo

**Comment by A7ocin** [comment]
> Hi,
> 
> Yes the `get_original` is a bit complicated, but here is a description of what it's doing:
> 
> 1. HMR recovers the camera [s, tx, ty] in the input image frame of 224 x 224 (actually in a normalized space, of [-1, 1] corresponding to this input). However the original image is not always 224x224, we scaled the image and cropped them for eg using openpose detection so we have the person centered in a 224x224 region.
>    These scale and crop parameters were saved as `proc_param`, where `scale` is the scale factor, and `start_pt` is the crop starting point after preprocessing.
> 2. `get_original` recovers the rendering camera settings s.t. it overlays the person in this original image, undoing the scale and crop. I'm using the OpenDR renderer s.t. the camera is always at identity, and I just need to specify the image size, focal length, and principal point, to render an arbitrary mesh in the world coordinate. So you need to figure out the focal length and principal point, and the `z` translation of the human body:
> 
> * Because OpenDR is a perspective camera (but HMR recovers weak-persepective), I make an assumption about the focal length and to recover the global `z` translation of the mesh in the world coordinate. (The scale `s` that HMR recovers is essentially `focal_length/z`.) I also "undo" the scaling done to the original image here.
> * Then Adjust the principal point of the camera s.t. it's on the center of the bounding box in the original input image space.
> 
> Hope this helps.

Hi, I'm still struggling to understand what the three camera settings mean (before and after get_original). Is there a way to retrieve the relative position of the camera with respect to the model?

**Comment by foermozhu** [comment]
> > Hi,
> > Yes the `get_original` is a bit complicated, but here is a description of what it's doing:
> > 
> > 1. HMR recovers the camera [s, tx, ty] in the input image frame of 224 x 224 (actually in a normalized space, of [-1, 1] corresponding to this input). However the original image is not always 224x224, we scaled the image and cropped them for eg using openpose detection so we have the person centered in a 224x224 region.
> >    These scale and crop parameters were saved as `proc_param`, where `scale` is the scale factor, and `start_pt` is the crop starting point after preprocessing.
> > 2. `get_original` recovers the rendering camera settings s.t. it overlays the person in this original image, undoing the scale and crop. I'm using the OpenDR renderer s.t. the camera is always at identity, and I just need to specify the image size, focal length, and principal point, to render an arbitrary mesh in the world coordinate. So you need to figure out the focal length and principal point, and the `z` translation of the human body:
> > 
> > 
> > * Because OpenDR is a perspective camera (but HMR recovers weak-persepective), I make an assumption about the focal length and to recover the global `z` translation of the mesh in the world coordinate. (The scale `s` that HMR recovers is essentially `focal_length/z`.) I also "undo" the scaling done to the original image here.
> > * Then Adjust the principal point of the camera s.t. it's on the center of the bounding box in the original input image space.
> > 
> > Hope this helps.
> 
> Hi, I'm still struggling to understand what the three camera settings mean (before and after get_original). Is there a way to retrieve the relative position of the camera with respect to the model?

Hi，I also miss this problem. I don’t know the role of these three camera parameters. I hope I can get your help, thank you very much.In the paper the author  wrote that the camera parameters R  ，s，t were recovered，but i find it was s，tx，ty，where R ？and how can i get it？
Thank you very much！

**Comment by Yuliang-Zou** [comment]
@foermozhu R is included in the global rotation parameter of SMPL

**Comment by foermozhu** [comment]
Thanks for your reply.
And is the first three&nbsp;parameters of pose&nbsp; ?
The axis angle representation of the root joint point---pelvis?
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akanazawa/hmr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 上午10:31
收件人:&nbsp;"akanazawa/hmr"<hmr@noreply.github.com&gt;;
抄送:&nbsp;"张亚凤"<1067102456@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [akanazawa/hmr] Compensation for changing camera parameters in a video sequence (#23)





 
@foermozhu R is included in the global rotation parameter of SMPL

**Comment by Yuliang-Zou** [comment]
It should be the axis angle of the root joint if I remember it correctly.

**Comment by foermozhu** [comment]
Thanks very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akanazawa/hmr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 上午10:39
收件人:&nbsp;"akanazawa/hmr"<hmr@noreply.github.com&gt;;
抄送:&nbsp;"张亚凤"<1067102456@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [akanazawa/hmr] Compensation for changing camera parameters in a video sequence (#23)





 
It should be the axis angle of the root joint if I remember it correctly.
