### ISSUE TITLE
Save output 3D model.

### ISSUE THREAD

**Issue by sree3333** [akanazawa/hmr#26]
Hi Thanks for this brilliant Project.
I am having issue with saving the 3D model from the project.
Could you please tell me steps how to save the resulted 3D model.

Thanks

**Comment by hejinying** [comment]
# save mesh
    face_path = './src/tf_smpl/smpl_faces.npy'
    faces = np.load(face_path)
    obj_mesh_name = './test.obj'
    with open(obj_mesh_name, 'w') as fp:
        for v in verts[0]:
            fp.write( 'v %f %f %f\n' % ( v[0], v[1], v[2]) )

        for f in faces: # Faces are 1-based, not 0-based in obj files
            fp.write( 'f %d %d %d\n' %  (f[0] + 1, f[1] + 1, f[2] + 1) )

**Comment by akanazawa** [comment]
Thanks for your interest!
The command above works great, but another approach is to use  packages like pymesh and [its save mesh utilities](https://pymesh.readthedocs.io/en/latest/basic.html#saving-mesh), which will let you save in different file types.
