### ISSUE TITLE
questions about learning rate 

### ISSUE THREAD

**Issue by penincillin** [akanazawa/hmr#27]
Hi,
I have two questions about the learning rate

1)  In your paper, you said the learning rate of encoder is set to 1e-5, but in your code, the learning rate is set to be 1e-3? So I am puzzled about this and wondering which one is the actual learning rate I should use?
2) Have you adjusted the learning rate during training?  I haven't found this kind of operation in your code.

Thanks.

**Comment by akanazawa** [comment]
Hi,

The setting in [`do_train.sh`](https://github.com/akanazawa/hmr/blob/master/do_train.sh) is the setting used for the model. There the learning rate is 1e-5. 

No I did not play around with learning rate adjustment. I'm sure it would help. 

Thanks,
