### ISSUE TITLE
The version of the protobuf (maybe caused by tensorflow)has problems. How to fix it?

### ISSUE THREAD

**Issue by tingxueronghua** [akanazawa/hmr#29]

**Comment by tingxueronghua** [comment]
now I find the problem was caused by tf.contrib.slim. Is the version of the slim the cause of the problem?

**Comment by akanazawa** [comment]
Hi, this sounds like some issue with tensorflow, please provide more information but I think these issues are best referred to at tensorflow people.

Best,

Angjoo
