### ISSUE TITLE
The problem about the version of libprotobuf

### ISSUE THREAD

**Issue by tingxueronghua** [akanazawa/hmr#30]
I try to use hmr on my TX2 flashed with JetPack 3.1.
The tensorflow I am using is tensorflow 1.6(which is a strange version, but does support python 2 and Cuda8.0). And it does work on my machine.
All seemed to be normal until I tried to run the demo. The result follows:

[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/arm-opt/genfiles/tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/arm-opt/genfiles/tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.cc".)
Aborted (core dumped)

Is anybody here? Who can help me?

**Comment by akanazawa** [comment]
This is an issue with protobuf and tensorflow and not related to this code base. I have not tested this on TF1.6.

I have ran in to a similar issue before though, TF can't find protobuf 3.5. Make sure it's installed, if it is I have seen a common issue where it is installed but there are two protobufs in the system and TF not finding the right one. 
My advice is start from scratch with a clean virtualenv. 

Best of luck,

aj
