### ISSUE TITLE
Where is the global rotation of R referring to the paper？

### ISSUE THREAD

**Issue by Superlee506** [akanazawa/hmr#32]
Hi, in the paper, I find the the parameters contains global rotation R (3x3), however I can't find it in the code. Do I miss something?
![image](https://user-images.githubusercontent.com/13114675/45474174-955bb880-b76b-11e8-810e-a8991f910c94.png)

**Comment by akanazawa** [comment]
Global rotation is specified by the first 3D of the theta (72-D), as axis-angle representation, as per the SMPL convention. 
If you read up on how SMPL works from their README I think this will be clearer. 

Best,

aj
