### ISSUE TITLE
Using surface points to generate SMPL Shape

### ISSUE THREAD

**Issue by ingramator** [akanazawa/hmr#35]
Is it possible within this framework to use predictions from a framework like [DensePose](https://github.com/facebookresearch/DensePose) to output the shape prediction like seen in this repository?

**Comment by akanazawa** [comment]
This approach is feed-forward, to use output of DensePose, an optimization based refinement approach of our previous work SMPLify: http://smplify.is.tue.mpg.de/ would be a better fit.

There we used 2D keypoints to fit SMPL pose and shape parameters. You can use HMR output of the pose as initialization, and optimize for pose and shape that maximizes the fit to dense pose.
