### ISSUE TITLE
Frame of reference for 3d keypoints

### ISSUE THREAD

**Issue by vasavig** [akanazawa/hmr#43]
What is the frame of reference with respect to which the 3d keypoints are found? Is this frame of reference same across any input image?

I am trying to do perspective correction on the 3d keypoints. I need to know the frame of reference to do this. Thanks in advance!

**Comment by akanazawa** [comment]
Hi,

I'm not exactly sure what you mean by frame of reference. HMR is object-centric, so the camera is always at identity. Do you mean the global coordinate frame? It's that of SMPL's bc it's object-centric. The camera never rotates, instead the person rotates (and gets translated in the image plane).
