### ISSUE TITLE
The question about the mosh data

### ISSUE THREAD

**Issue by TigerWj** [akanazawa/hmr#47]
Hello, I have download the Mosh dataset, and I have learn that there many argument of pose and shape in the dataset.
But, I want to know  **the proportion of male and female in data** ,it is important for me. I hope you can help me solve this problem，thank you!

**Comment by akanazawa** [comment]
I don't think I have the meta data for gender in that file, since I was not the one to Mosh these datasets. Please refer to the original dataset creators. 

Best,

Angjoo
