### ISSUE TITLE
Running this code on videos

### ISSUE THREAD

**Issue by vasantteja** [akanazawa/hmr#49]
Hi Team,

I was reading this paper and found that you presented this code for videos along with images. I am interested to learn how are you training this code on videos? Is it the same way as we do for images or do you have any additional steps for running this on videos?

Thanks,
Teja

**Comment by akanazawa** [comment]
Hi Teja,

In this version, I just ran the model on each frame independently, so no specific training on videos is done. We have a recent work that does train on videos, we're planning on code release end of January!

Thanks!

Angjoo
