### ISSUE TITLE
Using 3D labels!! exit(1)

### ISSUE THREAD

**Issue by buaacyh** [akanazawa/hmr#5]
Hi,akanazawa,

First, I want to appreciate your so clear explanation, it's the most wonderful git I had seen.
I follow your tips without any problem until reaching the final step. When I input "sh do_train.sh", the terminal output is 

Using 3D labels!!
Dont run this without any datasets with gt 3d
> ~/hmr/src/data_loader.py(134)get_loader_w3d()
    133             import ipdb; ipdb.set_trace()
--> 134             exit(1)
ipdb>

I dont know what's the warning means, it's the issues of my used datasets? I used lsp, lsp_ext, mpii and human36m dataset, not all datasets you mention. 

Thank you very much~~

**Comment by buaacyh** [comment]
I find the reason.
When I input the H36M .tf file, I didn't change the name and dir. However, in the data_loader.py/get_loader_w3d, at line124, my 'files_yes3d' always is []. Then I find in data_utils.py, at line123, I need change the dir of H36M.tf to 'tf_records_human36m_wjoints'. 
Then I pass!

**Comment by akanazawa** [comment]
Ah nice! But one core issue it that I uploaded the wrong h36m tfrecords data. (The h36m data should've contained the directory `tf_records_human36m_wjoints` to begin with).

I'm glad you figured it out but I'd do it again with the proper tfrecords. Please re-download the H36M [here](https://drive.google.com/open?id=1tquavoVWSdGeOn9P6zwoffIMoCRElzEO) and try again.

Also, that message comes up when you have the flag `--use_3d_label True` on, but no tfrecords dataset with ground truth 3D data is loaded. So even without H36M, if you have MPI-INF-3DHP it should've worked. Anyway I suggest you try with the new H36M data.

Thanks!
