### ISSUE TITLE
The number of datasets is in correct.

### ISSUE THREAD

**Issue by viperit** [akanazawa/hmr#52]
I have download the **Mosh Data** (named as **mosh_data.tar.gz** if you have tried) dataset mentioned in `https://github.com/akanazawa/hmr/blob/master/doc/train.md`.

However, when i use it i have found the amount of poses saved in **neutrSMPL_CMU** and **neutrSMPL_H3.6** is larger than the number noted in paper. Only **neutrSMPL_jointLim**(i presume that is the PosePrior dataset in paper) is right.

AKA, as show in below.

- neutrSMPL_CMU, 3, 934, 267 (3.9 M) in download datset, 390, 000 (150K) noted in paper.

- neutrSMPL_H3.6, 1, 872, 173 (1.8 M) in download datset, 150, 000 (150K) noted in paper.

- neutrSMPL_jointLim, 181, 968 (180 K) in download datset, 180, 000 (180K) noted in paper.

**Comment by viperit** [comment]
@akanazawa

**Comment by akanazawa** [comment]
Hi,

It's probably because the framerate of these mocap sequences are quite high and the data is quite correlated, so I probably subsampled these examples by 10? Numbers look like they match up for CMU and H36M. For H36M, you also need to take out test subjects.

**Comment by viperit** [comment]
Ok! Thank you for your reply! @akanazawa
