### ISSUE TITLE
How to run this code in real time

### ISSUE THREAD

**Issue by intvo** [akanazawa/hmr#53]
Thank you for your hard word, I run your code and everything works fine but I want to run this code in real time using my webcam? 
how can I do that? 
thanks

**Comment by akanazawa** [comment]
Hi @intvo,

Thanks for your interest. Although the model does the prediction from cropped image to 3D models in real time, this doesn't account for time to setup and load the models, and also for rendering the mesh. This is a research demo code so it does not include functionality for this and it will require some more engineering to make it real time. 
Actually the biggest bottleneck is probably rendering, especially with OpenDR. If you wanted to do this you need a different renderer that's faster. 
To run it from webcam you would have to setup a process that pre-loads and sets up the models, and call the predict function in a loop etc. 

Happy to put a link in this repo's main page if you work on this and put it on github! (or anywhere)

Good luck,

Angjoo

**Comment by aalzooke** [comment]
can you please try to do it in real time
