### ISSUE TITLE
Same time to run demo on GPU or CPU

### ISSUE THREAD

**Issue by vasavig** [akanazawa/hmr#54]
I did not observe any difference in speed when I run the demo command on a single image either using the CPU or the GPU version of tensorflow. Is this expected?

**Comment by akanazawa** [comment]
Hi,

Are you sure the GPU was used? It's possible that for a single image the setup time takes substantially more that you don't notice the difference. The demo is just intended to show how to make the code work, so I have not tested this, but there is a significant difference doing training between CPU and GPU for sure.

Best,

Angjoo

**Comment by vasavig** [comment]
Thanks for the response! Right now, I am running the demo command on a bunch of frames, once for each, to get the 3d keypoints for each. I am guessing that this approach is running some code which can probably be shared among all the runs. I am new to tensorflow, so I am having trouble understanding the code. 

Could you please briefly explain what set up are you talking about and what results can be reused if I were to get 3d keypoints for a bunch of images?
