### ISSUE TITLE
Is there approach to convert between the 19 joints and the original SMPL's 24 joints?

### ISSUE THREAD

**Issue by xuehy** [akanazawa/hmr#57]
I am now using your code to produce the 19 joints. However, the joints are different from the original SMPL's 24 joints. I am trying to port the 19 joints to the Unity3D software, but Unity3D is based on the 24 joints model. Can you tell me how to convert between the joints?

Thank you very much!

**Comment by xuehy** [comment]
I find it. It is the J_transformed variable. However, I still have a question: what is the order of the 24 joints?

**Comment by Yuliang-Zou** [comment]
I think J_transformed is still the cocoplus or lsp joint.

**Comment by HelloEgg** [comment]
Hi @xuehy . How did you convert axis-angle to euler rotations in Unity humanoid rig? 
The code I used was

from scipy.spatial.transform import Rotation as R
r = R.from_rotvec(rotationalVector)

where rotationalVector are 72 pose parameters (axis-angle) of SMPL.

However, I tried copying euler angles to rig but pose does not look same as original mesh.

Do you have any idea?``

**Comment by acoMCMXCVI** [comment]
@HelloEgg  did you find solution for your issue? I also trying to find way how to use pose parameters to make pose in engine or some other 3d software.

Thank you
