### ISSUE TITLE
How to get the value of pose from verts [0]?

### ISSUE THREAD

**Issue by Vova-B** [akanazawa/hmr#59]
If we consider verts [0] as an analogue of smpl, then I would like to get such fields as in smpl, pose, betas, trans, etc. How can I get these fields for verts [0]?

**Comment by akanazawa** [comment]
Hi, 

See https://github.com/akanazawa/hmr/blob/8785764a9fb8e5cc88e1c2f283f47782bdcf28fd/demo.py#L131
theta is the 85D that holds [camera (3), pose (72), shape (10)], where pose and shape are equivalent of SMPL.

Best,

Angjoo

**Comment by Vova-B** [comment]
@akanazawa Thanks. But how i can get pose an trans from theta If theta is a ndarray(1, 85). How can I get separate values ​​for pose (72) and trans (10) from theta? 
![default](https://user-images.githubusercontent.com/35993213/50217130-e85f9000-0398-11e9-87fb-a88e6622e793.PNG)

**Comment by akanazawa** [comment]
Try 
```
camera = theta[:3]
pose = theta[3:3+72]
shape = theta[-10:]
```
?

Best,

Angjoo
