### ISSUE TITLE
there is somthing wrong with tfrecord type hum3.6M dataset

### ISSUE THREAD

**Issue by MandyMo** [akanazawa/hmr#6]
the meta/has_3d and mosh/gt3d is not exist in the human3.6M dataset.

can you reupload the dataset, thankyou!

**Comment by danache** [comment]
Hey I got the same problem!
when I remove hm36 in do_train.sh, the problem turn to disappear.How could we solve the problem?

**Comment by jameel-malik** [comment]
I encountered same problem with human3.6m.

**Comment by akanazawa** [comment]
Hi all,

Thanks for the report, yeah that was the old one,, I uploaded the right file: 
ight file [here](https://drive.google.com/open?id=1tquavoVWSdGeOn9P6zwoffIMoCRElzEO).
Could you please give this a try? 

Thanks!

Angjoo

**Comment by jameel-malik** [comment]
Hi,
It works !! 
Thanks.

**Comment by MandyMo** [comment]
@akanazawa I can't  thank you more.
