### ISSUE TITLE
How to get the value of pose from theta? 

### ISSUE THREAD

**Issue by Vova-B** [akanazawa/hmr#60]
How I can get pose an trans from theta If theta is a ndarray(1, 85). How can I get separate values ​​for pose (72) and trans (10) from theta?
![default](https://user-images.githubusercontent.com/35993213/50366973-fd514480-058d-11e9-9f60-c9a17a6a6d65.PNG)

**Comment by nicolasugrinovic** [comment]
@Vova-B in src/RunModel.py it shows the order in which the 85 SMPL parameters are ordered:
>             # cam = N x 3, pose N x self.num_theta, shape: N x 10
>             cams = theta_here[:, :self.num_cam]                
>             poses = theta_here[:, self.num_cam:(self.num_cam + self.num_theta)]
>             shapes = theta_here[:, (self.num_cam + self.num_theta):]
where num_cam=3 and num_theta=72. Then, you have that the first 3 numbers correspond to the intrinsic camera parameters (ordered like this [f, px, py]). 

The 10 numbers correspond to shape, not translation.

If I am not wrong, the translation (I suppose that by trans you mean translation) takes into account the cropping parameters as calculated in util/renderer.py function get_original.

**Comment by Arthur151** [comment]
From my understanding, the 3 parameters of cam in cams = theta_here[:, :self.num_cam]  is not just the normal [f, px, py]. Because in that way, we have no way to locate the human (x,y) location and scale in 2D images. Not to mention, use 2D keypoints to supervise the SMPL parameters. The cam parameters have to show the scale and trans_x, trans_y information.

**Comment by nicolasugrinovic** [comment]
@Arthur151 yes, I understand that you are correct. cams contain the following information:

>     # Theta is the 85D vector holding [camera, pose, shape]
>     # where camera is 3D [s, tx, ty]
Then the translation is calculated in the following way:
```
    cam_s = cam[0]
    cam_pos = cam[1:]
    flength = 500.
    tz = flength / (0.5 * img_size * cam_s)
    trans = np.hstack([cam_pos, tz])
```

**Comment by oxrider** [comment]
> @Arthur151 yes, I understand that you are correct. cams contain the following information:
> 
> > ```
> > # Theta is the 85D vector holding [camera, pose, shape]
> > # where camera is 3D [s, tx, ty]
> > ```
> 
> Then the translation is calculated in the following way:
> 
> ```
>     cam_s = cam[0]
>     cam_pos = cam[1:]
>     flength = 500.
>     tz = flength / (0.5 * img_size * cam_s)
>     trans = np.hstack([cam_pos, tz])
> ```

Does the trans convert the camera coordinate to world coordinate?

**Comment by nnop** [comment]
As eq2 of the paper states, `t` seems being in the image frame with pixel unit. 
![image](https://user-images.githubusercontent.com/23091984/199671003-95ff3b7b-d0f2-4094-8641-432563c61710.png)

If `(tx, ty)` is Euclidean translation in camera frame. Shouldn't the equation be:
![image](https://user-images.githubusercontent.com/23091984/199674773-1827affc-157a-48d5-bf4d-495437212ce4.png)

@Arthur151 @akanazawa

**Comment by lvZic** [comment]
> As eq2 of the paper states, `t` seems being in the image frame with pixel unit. ![image](https://user-images.githubusercontent.com/23091984/199671003-95ff3b7b-d0f2-4094-8641-432563c61710.png)
> 
> If `(tx, ty)` is Euclidean translation in camera frame. Shouldn't the equation be: ![image](https://user-images.githubusercontent.com/23091984/199674773-1827affc-157a-48d5-bf4d-495437212ce4.png)
> 
> @Arthur151 @akanazawa

I noticed this too. In fact, it should scale first, and then translation. However in HMR, it translation first.
By the way, i found the cam params converges worse during trainging process, and the poses and shapes converge better. Do u know how to work?

**Comment by lvZic** [comment]
> From my understanding, the 3 parameters of cam in cams = theta_here[:, :self.num_cam] is not just the normal [f, px, py]. Because in that way, we have no way to locate the human (x,y) location and scale in 2D images. Not to mention, use 2D keypoints to supervise the SMPL parameters. The cam parameters have to show the scale and trans_x, trans_y information.

I found the cam params converges worse during trainging process, especially the scale,  and the poses and shapes converge better. Do u know how to work?

**Comment by Arthur151** [comment]
@nnop ,
I guess the reason is that we want to disentangle the training of scale and translation.
If the equation is s(rx+t), the learning of translation and scale would affect each other. We don't want that. We want the gradiants of different factors to flow independently. 
Glad to join this interesting discussion. 
Best,
Yu

**Comment by nnop** [comment]
@Arthur151 
https://github.com/akanazawa/hmr/blob/f149abeb0a7e2a3412eb68274a94a9232f7cb667/src/tf_smpl/projection.py#L25-L29

It's reasonable to disentangle scale and translation. I think it would be better.
But the implementation is first translate then scale, which is actually:
![image](https://user-images.githubusercontent.com/23091984/199674773-1827affc-157a-48d5-bf4d-495437212ce4.png)
And this isn't consistent with the paper.

Is this a bug? @akanazawa

**Comment by akanazawa** [comment]
Hi I actually meant to implement it separately as sX + t, but did s(X+t) instead by accident that I discovered later that makes projecting it back into the image more complicated than it has to 🙈

The fix is easy try it!

A

**Comment by nnop** [comment]
Thanks for your clarification.
