### ISSUE TITLE
Could you please tell me how could I recovery the video sequence order of SMPL parameters in 'neutrSMPL_H3.6' and make correspondence with the original video in Human3.6M dataset?

### ISSUE THREAD

**Issue by Arthur151** [akanazawa/hmr#62]
Thanks for your efforts! This is really a great work! 
Downloadthe 'neutrSMPL' file your provided. I am confused with how to make each pairs of SMPL parameters correspond to a frame of original video, like 'S1/Directions 1.60457274'. 
Could you please tell me how to establish this correspondence, which is between SMPL parameters and corresponding frame of original video in Human3.6M?
Looking for your reply!
Merry Christmas!

**Comment by Arthur151** [comment]
Besides, could you please tell me the why these are additional files, like 'Directions 1_cam0_aligned.pkl'  containing 'new_poses'?
What is that???

**Comment by akanazawa** [comment]
Hi,

The new_poses in those `cam*_aligned.pkl` files should correspond to the pose that aligns with the image.

Thanks,

ANgjoo

**Comment by qiqiApink** [comment]
@Arthur151 Hi, can you tell me where I can download files like 'Directions 1_cam0_aligned.pkl' please? I can't find them. Thx!

**Comment by akanazawa** [comment]
I think those are from the human36m dataset, which the original authors do not want them to be mad available anymore unfortunately.

Best,

A
