### ISSUE TITLE
What's the origin of coordinate of SMPL?

### ISSUE THREAD

**Issue by Superlee506** [akanazawa/hmr#64]
![test01](https://user-images.githubusercontent.com/13114675/51440119-567fd580-1cfe-11e9-8e5b-06db96db0058.png)
When I visualized the SMPL in meshlab, I find the origin of coordinate isn't the center of pelvis(root). 
However in the human3.6m, the origin of the coordinate is pelvis(root). Do we need some pre-process before we calculate the loss3d?

Thansk.

**Comment by akanazawa** [comment]
Yes the training data aligns the 3D joints by root due to this reason: https://github.com/akanazawa/hmr/blob/8785764a9fb8e5cc88e1c2f283f47782bdcf28fd/src/ops.py#L50

Best,

Angjoo
