### ISSUE TITLE
About the human36m 

### ISSUE THREAD

**Issue by weigq** [akanazawa/hmr#65]
Hi, could you provide some code of generating the human36m tfcods? I want to do some modifications on the input images. 
Thanks!

**Comment by hammad001** [comment]
+1

**Comment by ChenyuGao** [comment]
+1

**Comment by ryoppippi** [comment]
I have a question
I opened the download page of HUman3.6, but which data should I download? @akanazawa

**Comment by eshafeeqe** [comment]
+1

**Comment by kemangjaka** [comment]
+1

**Comment by akanazawa** [comment]
There is now a version of this in our human dynamics paper repo: 

The preprocessing code is the same as the one I used for HMR: https://github.com/akanazawa/human_dynamics/tree/master/src/datasets/h36

[The tfrecords packing script there ](https://github.com/akanazawa/human_dynamics/blob/master/src/datasets/h36_to_tfrecords_video.py) are for video, but it's a minor modification from that to go to the single image version, if you follow the same <dataset>_to_tfrecord.py in this repo.

**Comment by eshafeeqe** [comment]
Hi @akanazawa, 

I didn't check the code yet. Anyway thanks a lot for an alternate way of pre-processing h36 data. It will be really helpful for other researchers like me to catch and work on top of your work. 

Thanks and Regards, 
Shafeeq E

**Comment by Karol-Perec** [comment]
@eshafeeqe Hi, did you magange to edit the code for packing images info .tfrecord? If yes, could you please share?

**Comment by eshafeeqe** [comment]
@Karol-Perec  No, I didn't get time for trying it out
