### ISSUE TITLE
Compatibily

### ISSUE THREAD

**Issue by Ipuch** [akanazawa/hmr#68]
Hi,

I like tro try your code on my Windows machine. However, I can't find the required versions for windows.

Tensorflow for python 2.7 is only available for mac and Linux. Can you tell me if your app works with python 3.6 on windows?

Best regards,

Pierre

**Comment by akanazawa** [comment]
Sorry, I never tested this in Windows. It's not supported. Happy to link to your repo if you figure out how to. 

Thanks!

Angjoo
