### ISSUE TITLE
Why is the silhoutte inclined?

### ISSUE THREAD

**Issue by saturosfz** [akanazawa/hmr#71]
Dear author, thank you for your great work. I downloaded the tfrecords, and plot the 3D points of SMPL model. I directly use the SMPL vertices without transforms. The plot seems great from the front view, but the sihoutte is inclined.
![bbbb](https://user-images.githubusercontent.com/10704275/53161141-5b3cef80-3604-11e9-927b-b1a3aebe3274.jpg)
![000000 5](https://user-images.githubusercontent.com/10704275/53161176-70198300-3604-11e9-8271-1c466efa9c50.jpg)
The first is the tilted silhoutte, and the second is the corresponding image. From the image I think the man is standing straight. Is there something wrong with my plot? Thank you!

**Comment by akanazawa** [comment]
Hi,

This could be two things:
1. Ambiguity, the model is cheating to get the right hight by slightly tilting people like this. It's not explicitly recovering the floor, so things like this can happen. 

2. The global coordinate frame is slightly off, in this world, where that feet is might be the floor and if you applied that transformation it would be up right. You could double check this with the training data, see if it looks up right from side view. 
I think it's a problem of both, when you visualize the ground truth H36M pose I remember it still looks somewhat tilted..

Best,

Angjoo

**Comment by neonb88** [comment]
Dear Ms. Kanazawa,

Our team has noticed many cases of this; HMR captures the pose well, but the resulting SMPL model is often leaning forward.  Is this a result of training data also being taken leaning forward?

Thanks!

**Comment by akanazawa** [comment]
Yes there are two issues that can lead to, one due to depth ambiguity (hard to resolve) second due to the coordinate space of the training data. I think it's a mixture of the two. There is inherent ambiguity that makes this problem difficult.
