### ISSUE TITLE
About the the Penn Action Dataset

### ISSUE THREAD

**Issue by ChenyuGao** [akanazawa/hmr#73]
Hello, I read your new paper "Learning 3D Human Dynamics from Video", but I don't know where to download the Penn Action Dataset. I forces on the sports datset.
By the way, when your code will be released?
Thanks for your work!

**Comment by A7ocin** [comment]
Hi, you can download the Penn Action Dataset from the [official website](https://dreamdragon.github.io/PennAction/).

Nicola

**Comment by ChenyuGao** [comment]
> Hi, you can download the Penn Action Dataset from the [official website](https://dreamdragon.github.io/PennAction/).
> 
> Nicola

Thank you very much!

**Comment by SkyeLu** [comment]
Hi, do you know how to read the mat file in PennAction Dataset? I'v tried using scipy.io.loadmat and h5py.File, both methods failed. Thanks. @ChenyuGao @A7ocin

**Comment by ChenyuGao** [comment]
I just use it as follow in python3:

import scipy.io as scio
sample_label_file = os.path.join(label_dir, '0001.mat')
sample_label_data = scio.loadmat(sample_label_file)

"sample_label_data" is a dict

**Comment by A7ocin** [comment]
I think you should take a look at Kanazawa's new repository, called "human_dynamics" 😉

**Comment by SkyeLu** [comment]
Thank you guys! I just found that my mat files get corrupted while decompressing from the .tar.gz file. Thank you again! @ChenyuGao @A7ocin
