### ISSUE TITLE
reconst error

### ISSUE THREAD

**Issue by woshildh** [akanazawa/hmr#77]
Hello, I want to evaluate to get the reconst error, what should I do?

**Comment by nicolasugrinovic** [comment]
Could you do it? If I'm not wrong, what you are looking for is [here](https://github.com/akanazawa/hmr/blob/master/src/benchmark/evaluate_h36m.py)

**Comment by woshildh** [comment]
I didn't know reconst error is MPJPE-PA before. Thanks very much
