### ISSUE TITLE
Can't install opendr due to "cannot find -lOSMesa "

### ISSUE THREAD

**Issue by zsw667291** [akanazawa/hmr#84]
run code pip install -r requirements.txt
it told me 
"  /usr/bin/ld: cannot find -lOSMesa
  /usr/bin/ld: cannot find -lGL
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for opendr"

how do I fix it?

**Comment by neonb88** [comment]
Try doing `pip install opendr==0.77` within a virtualenv on python2.  Please follow Ms. Kanazawa's instructions on the README as carefully as possible.

**Comment by svarnypetr** [comment]
Sorry for posting on a closed issue, but why is it then not added to the `requirements.txt` ?

**Comment by akanazawa** [comment]
Updated, ty. Unfortunately I'm not on this all the time. I always welcome pull requests :)
