### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by yifengji** [akanazawa/hmr#85]

**Comment by yifengji** [comment]
when I tryed
        with open(pkl_path, 'rb') as f:
               dd = pickle.load(f)
        # Mean template vertices
        self.v_template = tf.Variable(
            undo_chumpy(dd['v_template']),
            name='v_template',
            dtype=dtype,
            trainable=False)
I got new issue：
![image](https://user-images.githubusercontent.com/30115993/56480991-332c1880-64ef-11e9-8f6f-8fe24e3de325.png)

**Comment by crypticsymmetry** [comment]
have this issue as well. how did you fix this? thanks
