### ISSUE TITLE
can you share the human 3.6 M dataset to me? I I have registered on the official website,But the administrator never responded to me.

### ISSUE THREAD

**Issue by yifengji** [akanazawa/hmr#88]

**Comment by zsw667291** [comment]
I also encountered such a problem.I want to run do_train.sh, i don't have the tf_records_human36m.tar.gz
T-T

**Comment by maoyali** [comment]
+1

**Comment by akanazawa** [comment]
Unfortunately I can't provide the dataset due to licensing reasons. 
You can train without human3.6m, just remove `h36m` from the command. 

Soon, we will make the training code for our CVPR'19 paper, and this will contain some code for processing the raw human3.6M dataset (without mosh)
