### ISSUE TITLE
How can I generate moshed data by myself?

### ISSUE THREAD

**Issue by danache** [akanazawa/hmr#9]
In train.md I see that you generate mosh data for(CMU dataset, human3.6m and mpi-3d, but in the page[]( http://mosh.is.tue.mpg.de/).I can't find how to generate mosh data.So how can I generate moshed data by myself?

**Comment by akanazawa** [comment]
Please consult the authors of MoSh: http://mosh.is.tue.mpg.de/

**Comment by RanFeng** [comment]
Thank you very much!

**Comment by Karol-Perec** [comment]
@danache Did you figured out how to generate mosh data on raw human3.6m dataset?
