### ISSUE TITLE
Extract 3D Joint positions

### ISSUE THREAD

**Issue by Shoulder95** [akanazawa/hmr#90]
I am trying to achieve something that looks like this 
![gitproblem](https://user-images.githubusercontent.com/43409969/57303872-88b31880-70de-11e9-9923-eb4b7109b792.png)

I have extracted joints3D and the rotation matrices from theta, but when I plot the points I don't get anything that looks even remotely close to what I get from the figure created by demo.py.

Does anyone have any suggestion to how I could achieve this?

**Comment by justinmacp** [comment]
Might be a little late.

Essentially you want to take joints3d from demo.py (line 131) and plot that. The connections between joints (edges) would be as follows:
edges = [[0,1],[1,2],[2,3],[3,4],[4,5],[2,8],[3,9],[8,9],[6,7],[7,8],[9,10],[10,11],[8,12],[9,12],[12,13],[13,14],[14,15],[14,16],[13,17],[13,18]]

Let me know if you need any further help
