### ISSUE TITLE
neutrSMPL_H3.6 is not in mosh data

### ISSUE THREAD

**Issue by eshafeeqe** [akanazawa/hmr#91]
Hello akanazawa, 

First of all thanks a lot for making this awesome work into public. 

I have download the Mosh Data (named as mosh_data.tar.gz if you have tried) dataset mentioned in https://github.com/akanazawa/hmr/blob/master/doc/train.md. 

I just found only two sub-folders inside this (neutrSMPL_CMU and neutrSMPL_jointLim) and neutrSMPL_H3.6 is missing. 

I am just wondering is it missing because I am looking it for  wrong place or I missed something. 

Thanks and Regards, 
Shafeeq E

**Comment by dangpugui** [comment]
I also encountered this problem. SO do you understand what is going on now?

**Comment by eshafeeqe** [comment]
I think Its due to licensing issues all data related to Human3.6 withdrawn.

**Comment by akanazawa** [comment]
@eshafeeqe is right, unfortunately this data is not available anymore due to licensing. Sorry.

**Comment by Rhyssiyan** [comment]
@akanazawa The neutrSMPL_H3.6 file you created is very important to reproduce the result for recently published papers.  So is there any possible solutions to make it accessible? For example, is it ok to upload only the smpl parameters. If it's still illegal, is it possible to upload neutrSMPL_H3.6 to human3.6m site? 

Thanks.

**Comment by akanazawa** [comment]
I would like to but I do not own the license, I am not the one who is putting a stop to this. The license lies with the Human3.6M authors, but unfortunately it is out of my control.
