### ISSUE TITLE
only 2D skeleton displayed, 3D mesh and diff vp is dark

### ISSUE THREAD

**Issue by sloopdoom** [akanazawa/hmr#93]
I installed tensorflow 1.3 , download the trained model,   the output windows's second row is three dark windows. 3D mesh overlay seems not work yet.

**Comment by sloopdoom** [comment]
I guess it is the tesorflow gpu  or the docker problem,   docker not support gui, it is not recommend to use docker run HMR,  it work well to directly install HMR without docker

**Comment by zhouyan09** [comment]
@sloopdoom ，Hi , I meet with the same problem. I just clone the git  repository and run the demo command, but  3D mesh and diff vp is dark. 
My environment is 
tensorboard==1.14.0
tensorflow==1.11.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
tensorflow-tensorboard==0.1.8
I have tried with python2.7 and python3.6, but all gave the same dark images.
Can you give me some advice?Thank you.
