### ISSUE TITLE
How to match RGB value with the vertices? 

### ISSUE THREAD

**Issue by layumi** [akanazawa/hmr#94]
Hi @akanazawa ,

Thank you for your great code!  I am new to the 3D reconstruction.
I have a question about how to match the RGB value in 2D image with the 3D vertices (x,y,z) that your code generates.

The naive idea that I have is to match the 2D pixels and the 3D vertices who has the smallest depth. Do you have any suggestion or code recommendation?

Thank you very much.

**Comment by akanazawa** [comment]
Hi, I think my answer here: https://github.com/akanazawa/hmr/issues/110#issuecomment-526178620 might help with this, let's consolidate the discussions there and i'm closing this issue. Thanks.
