### ISSUE TITLE
Extracting volume for each body part

### ISSUE THREAD

**Issue by Gavriela** [akanazawa/hmr#95]
Hello,

The past days I have been testing HMR and it seems really interesting. Now, I am trying to find a way to compute volume for each part of the body. 
I know it has limitations, since it slims the body as I have seen in some images, but for now even an approximation of the volume would work for me. 

Any suggestions for that?

**Comment by akanazawa** [comment]
Something like this would be a good starting point: http://chenlab.ece.cornell.edu/Publication/Cha/icip01_Cha.pdf
