### ISSUE TITLE
How to correctly measure the running time?

### ISSUE THREAD

**Issue by saturosfz** [akanazawa/hmr#98]
First, thank the author for the meaningful repo.
I measure the running time of the core function ( line 131 of demo.py ), and the running time is 1 second, much longer than real-time standard. I have already enabled my GPU. Is there anything wrong with my measure?

**Comment by akanazawa** [comment]
Hi,

It's because the first time it runs it needs to load the model etc and those things take a long time. The second call of `model.predict` will run as reported in the paper.

Best,

Angjoo
