### ISSUE TITLE
72D Pose parameters

### ISSUE THREAD

**Issue by alirezag** [akanazawa/hmr#99]
Dear, 

I'm a big fan of HMR and was recently introduced to it by one of your colleagues. However I can't consistently recover the pose 24 joints encoded in the 72D vector. Are those encoded row major? so Joint1_x, joint1_y, joint1_z, joint2_x, joint2_y, joint3_z ? and what is the name of those joints in that order? Unfortunately, SMPL has no references of this.

**Comment by alirezag** [comment]
does anybody have any luck relating this 24 joints to body? the joint assignment i get is very different than the purported SMPL.

**Comment by jasonyzhang** [comment]
The 72D vector contains the rotations for the 24 joints in axis-angle representation, not cartesian coordinates.

**Comment by usideu-admin** [comment]
thanks turns out I had very bad accuracy due to inappropriate preprocessing of inputs

**Comment by ChenyuGao** [comment]
joints_list = ['Pelvis', 'L_Hip', 'R_Hip', 'Spine1', 'L_Knee', 'R_Knee', 
               'Spine2', 'L_Ankle', 'R_Ankle', 'Spine3', 'L_Foot', 'R_Foot', 
               'Neck', 'L_Collar', 'R_Collar', 'Head', 'L_Shoulder', 'R_Shoulder', 
               'L_Elbow', 'R_Elbow', 'L_Wrist', 'R_Wrist', 'L_Hand', 'R_Hand']
You can relate this to the SMPL paper.
